# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Article.create([{title: "One", body: "Aliquam venenatis arcu nec lorem consequat commodo. Praesent et elit purus. Duis pellentesque enim sit amet dignissim dignissim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque pharetra egestas consectetur. Aliquam orci nulla, dapibus semper dolor vel, vulputate vehicula lorem. Maecenas nisi lorem, facilisis sed luctus vulputate, efficitur egestas erat."},
{title: "Two", body: "Integer non iaculis erat, eu aliquam sapien. Sed sit amet lacus nunc. Sed vel diam luctus ante imperdiet aliquam vehicula at felis. Nullam dolor nisi, sagittis non vestibulum sed, commodo ac metus. In at nisi in ipsum porttitor gravida. Praesent lobortis mattis urna vehicula tristique. Morbi bibendum convallis volutpat. Nullam eu tempor purus. In ac aliquet leo. Fusce et dictum ligula. Nullam gravida iaculis imperdiet. Curabitur facilisis vitae lacus sed lacinia."}, 
{title: "Three", body: "Three Three"}, 
{title: "Four", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam viverra vulputate pulvinar. Curabitur eget tincidunt lectus, at accumsan elit. Proin vel velit tristique, venenatis tortor at, venenatis ligula. Mauris mattis pretium augue, non lacinia tellus gravida non. Donec nec rutrum ligula, at efficitur nisl. Etiam iaculis, ex ut gravida porta, eros massa consequat erat, quis lobortis urna tellus eget nisi. Curabitur congue sed arcu et posuere. Vivamus ut dapibus tortor, nec convallis justo. Curabitur eget dui sed ipsum dapibus lobortis in a ex. Etiam rhoncus, felis id semper consectetur, nisi tellus sagittis elit, id volutpat sem enim et leo."},
{title: "Five", body: "Praesent id nisi sollicitudin, ultricies metus sit amet, porta augue. Quisque interdum iaculis mi. Fusce tempor erat ipsum, molestie dapibus nisl mattis in. Donec porttitor ut velit in maximus. Aliquam sit amet pulvinar libero, eget dignissim arcu. Nulla cursus blandit mauris sodales rhoncus. Praesent elementum commodo auctor. Ut ac interdum libero. Aliquam finibus ut risus et consectetur."},
{title: "Six", body: "Aenean suscipit a augue id egestas. Nunc quam magna, sagittis et tellus at, imperdiet lacinia dui. Proin consequat mollis lacinia. Quisque in purus non nisi auctor sagittis. Nunc quis euismod libero, viverra cursus neque. Etiam egestas posuere velit. Nullam dictum orci enim. Aliquam ornare velit magna, in tempus sem sollicitudin vitae. Suspendisse potenti."},
{title: "Seven", body: "Phasellus porta lectus vel vehicula commodo. Donec hendrerit pretium sapien. Etiam facilisis eu quam non gravida. Nulla sollicitudin sem odio, eget tempus est vestibulum eu. In sapien ligula, consequat in auctor in, mollis quis quam. Sed nec consequat orci. Pellentesque vel nisl non mauris tempor congue id ac ex. Quisque in rhoncus mauris, sit amet tincidunt quam. Curabitur lectus eros, consequat sit amet nisl vehicula, aliquam facilisis velit. Donec tortor lectus, semper a consectetur a, vulputate nec urna. Nulla gravida sed sapien vitae pulvinar. Proin ornare nunc sed facilisis congue. Vivamus ornare vel leo sit amet feugiat. Morbi convallis nulla eu arcu scelerisque venenatis. Morbi dictum, risus ac faucibus rhoncus, ante lorem tristique enim, vel congue orci justo nec risus. Nulla non aliquam augue."},
{title: "Eight", body: "Suspendisse sollicitudin, nulla id ornare sollicitudin, nisl urna sodales magna, id bibendum elit nibh nec arcu. Nulla nec tristique nulla, nec tristique dolor. Curabitur accumsan pharetra dolor eu pulvinar. Vivamus diam tortor, finibus sit amet vulputate non, egestas quis urna. Etiam consectetur mollis justo. Nullam bibendum lectus urna, in sodales mauris consequat eu. Quisque sed dui non diam finibus efficitur."},
{title: "Nine", body: "Aenean fringilla lectus eu velit dapibus mollis. Morbi vel nunc a est ultricies volutpat. Nunc id maximus mi. Phasellus nec justo faucibus, scelerisque tortor non, volutpat sem. Mauris quis ex ut leo aliquam bibendum quis facilisis libero. Praesent imperdiet pharetra volutpat. Mauris sed vulputate leo. Mauris aliquam, lorem placerat scelerisque aliquam, turpis odio iaculis leo, quis posuere lectus dolor ut nibh. Praesent libero metus, accumsan nec egestas nec, ornare ut enim."},
{title: "Ten", body: "Nulla at felis ac augue efficitur faucibus. Integer viverra risus nibh, sed maximus est malesuada et. Vivamus sed feugiat massa, et viverra dolor. Fusce at tortor nec eros posuere feugiat. Suspendisse faucibus nibh ac commodo tempor. Nunc eget augue et mi auctor finibus eu vel nisi. Donec iaculis nisl eu lorem euismod mattis. Mauris a neque ut nulla consectetur dictum. Donec semper leo vel felis finibus, et egestas ipsum maximus. Sed elementum odio vitae rutrum condimentum. Integer nec enim ac dui viverra suscipit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla facilisi."}])